//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(HistoricoDetalleMetaData))]
    public partial class HistDetalleCRUD
    {
        public int IDHistorico { get; set; }
        public int IDProducto { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> IDContacto { get; set; }
        public int TipoCRUD { get; set; }
    
        public virtual CONTACTO CONTACTO { get; set; }
        public virtual HISTORICO HISTORICO { get; set; }
        public virtual TipoCRUD TipoCRUD1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
