//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(HistoricoMetaData))]
    public partial class HISTORICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORICO()
        {
            this.HistDetalleCRUD = new HashSet<HistDetalleCRUD>();
            this.HistDetalleEntradaSalida = new HashSet<HistDetalleEntradaSalida>();
        }
    
        public int ID { get; set; }
        public string fechaHora { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> tipoMov { get; set; }
        public string detalle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistDetalleCRUD> HistDetalleCRUD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistDetalleEntradaSalida> HistDetalleEntradaSalida { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual MOVIMIENTO MOVIMIENTO { get; set; }
    }
}
