//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistDetalleCRUD
    {
        public int IDHistorico { get; set; }
        public int IDProducto { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<int> IDContacto { get; set; }
        public int TipoCRUD { get; set; }
    
        public virtual CONTACTO CONTACTO { get; set; }
        public virtual HISTORICO HISTORICO { get; set; }
        public virtual TipoCRUD TipoCRUD1 { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
    }
}
