//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(HistoricoDetalleEntradaSalidaMetaData))]
    public partial class HistDetalleEntradaSalida
    {
        public int IDHistorico { get; set; }
        public int IDProducto { get; set; }
        public Nullable<int> IDSucursalEntra { get; set; }
        public Nullable<int> IDSucursalSale { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual HISTORICO HISTORICO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual SUCURSAL SUCURSAL1 { get; set; }
    }
}
