//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(HistoricoDetalleEntradaSalidaMetaData))]
    public partial class HistDetalleEntradaSalida
    {
        public int IDHistorico { get; set; }
        public int IDProducto { get; set; }
        public Nullable<int> IDSucursalEntra { get; set; }
        public Nullable<int> IDSucursalSale { get; set; }
        public Nullable<int> IDProveedor { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual HISTORICO HISTORICO { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual PROVEEDORES PROVEEDORES { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
        public virtual SUCURSAL SUCURSAL1 { get; set; }
    }
}
