//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SunriseBDEntities1 : DbContext
    {
        public SunriseBDEntities1()
            : base("name=SunriseBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
        public virtual DbSet<HistDetalleCRUD> HistDetalleCRUD { get; set; }
        public virtual DbSet<HistDetalleEntradaSalida> HistDetalleEntradaSalida { get; set; }
        public virtual DbSet<HISTORICO> HISTORICO { get; set; }
        public virtual DbSet<MOVIMIENTO> MOVIMIENTO { get; set; }
        public virtual DbSet<PAIS> PAIS { get; set; }
        public virtual DbSet<ProdSuc> ProdSuc { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<PROVEEDORES> PROVEEDORES { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SUCURSAL> SUCURSAL { get; set; }
        public virtual DbSet<TipoCRUD> TipoCRUD { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
