//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ProductoSucursalMetaData))]
    public partial class ProdSuc
    {
        public int IDProducto { get; set; }
        public int IDSucursal { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> cant { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
