//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ProductoSucursalMetaData))]
    public partial class ProdSuc
    {
        public int IDProducto { get; set; }
        public int IDSucursal { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> cant { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual SUCURSAL SUCURSAL { get; set; }
    }
}
